### ISSUE TITLE
printRow(true) and AddPage()

### ISSUE THREAD

**Issue by mdes** [fpdf-easytable/fpdf-easytable#11]
Hi,

When defining a table header thru `printRow(true)`, `AddPage()` does not output the header.
Note that it is working when a new page is output because the table reaches the page end.

I will appreciate you solving this issue (as you did it very quickly with the last issue I wrote!).

Thanks in advance,
Michel.

**Comment by fpdf-easytable** [comment]
Hi, 

Have a look at the example2.php. In it there is a table that is printed across multiple pages and the table header is printed in each page.

Cheers

**Comment by mdes** [comment]
Ok, thanks for your advice.

But there is an error in the documentation:
> function printRow ( [ bool $setAsHeader = false ] ) […] Remark: 1. In order to work, the table attribute split-row should set as true.

This attribute as to be set to `false`, not `true`!
Now, it is working form me.

In any case, many thanks for looking at my prose ;)

_Note: Very strange, but I already tested with the both values, and I didn't see any change about the header. Perhaps I'm becoming too old for coding ;)_

**Comment by fpdf-easytable** [comment]
Hi Michel,

You were right the documentation was wrong. I made the correction. 

About your note, probably you are getting old :-D Using example2.php, for the header set $table->printRow(true) and for the table attribute split-row, set it to true and you will see that the header is just printed once, set it back to false (default value) and the header is printed in each page.

Cheers
Dan
