### ISSUE TITLE
Escaping <

### ISSUE THREAD

**Issue by mdes** [fpdf-easytable/fpdf-easytable#12]
Hi,

How to escape `<` in `table->easyCell(text)`?

I generate a list of emails (like `"Jim" <sjim@any.com>`) from a database. Everything from `<s` is not output.

I inserted a space after the `<` as a turnaround, but this is not satisfactory.
Something like `\<` or `&lt;` could be solutions, specially the 2d one to have the possibility to insert `&nbsp;`…

Thanks,
Michel.

**Comment by fpdf-easytable** [comment]
Hi,

Fair comment... I will have a look.

Cheers

**Comment by fpdf-easytable** [comment]
Hi Michel,

Hey I set FPDF_easytable to escape the sequence '\<s' as '<s'. 

Please give it a go and report any bug.

Enjoy fpdf_easytable!

Cheers

Dan

**Comment by mdes** [comment]
Thanks for this modification… but it does not seem to work :(
`$cellValue = str_replace('<', '\<', $cellValue);
$table->easyCell(utf8_decode($cellValue),…`
output `"email starting with d" \<dani…@gmail.com>
"email starting with s" \
"email starting with a" \<albert…>`

**Comment by mdes** [comment]
Hi Dan,

Thanks a lot, it is working ;)

Cheers,
Michel.
