### ISSUE TITLE
Using printRow() in Header()

### ISSUE THREAD

**Issue by mdes** [fpdf-easytable/fpdf-easytable#13]
Hi,

I have to output a header whose content is varying depending on the 1st row of the page content, and which is formatted via easyCell.

I have to use printRow() to output my header, but it does not seems to work: something is looping somewhere.

Any idea how to solve this problem?

Regards,
Michel.

**Comment by fpdf-easytable** [comment]
Could you write a simple example of the situation you are describing?

**Comment by mdes** [comment]
Hi,

There is no more need for me because I used this way to get around of the issue #11.

Thanks following this wonderful extension ;)
Michel.

**Comment by fpdf-easytable** [comment]
Cool!

Dan
