### ISSUE TITLE
Newline in easyCell

### ISSUE THREAD

**Issue by mdes** [fpdf-easytable/fpdf-easytable#15]
Hi,

Newlines in the text of easyCell() generates a bad display in the Pdf file.

```
$table->easyCell(utf8_decode('<s "font-size:10;">EN SOUMETTANT…CI-DESSOUS.

<b>Conditions…</b>

En vous inscr…'), 'border:TLBR; colspan:5;');
	$table->printRow();
```

gives this (with Microsoft IE11, Microsoft Edge and Adobe Reader, but not with Google Chrome):
![image](https://user-images.githubusercontent.com/6514419/44653093-0d955080-a9ee-11e8-8bc8-a0b9c7b9f589.png)

Copying the newline character, it gives hex 0D0A.

Using `aaa\nbbb` explicitly does not solve the problem because the text `aaa\naaa` appear as is when displaying the Pdf.

Thanks helping me to avoid these unrecognized characters.
Michel.

**Comment by fpdf-easytable** [comment]
Hi Michel,

I use linux, however I think the problem you are having has to be relate to the encoding of the font you are using sometimes utf8_decode is not enough, use iconv instead (see the section on Fonts and UTF8 support in the easytable's documentation). Possible dirty hack would be to break down as follows:

    $table->easyCell(utf8_decode('<s "font-size:10;">EN SOUMETTANT…CI-DESSOUS.) . "

    " . utf8_decode('Conditions…') . "

    " . utf8_decode('En vous inscr…'), 'border:TLBR; colspan:5;');
    $table->printRow();

notice the new line character wrapped in quotation marks.

Cheers

Dan

**Comment by mdes** [comment]
Hi Dan,

Thanks a lot for your idea: it remembers me the usage of "\n" in PHP (double quotes!).
So I found the solution by using `"\n \n"` to skip a blank line. Note that the space between the 2 newlines is required (I don't know why).

My coding is now:
```
$table->easyCell(utf8_decode('<s "font-size:10;">EN SOUMETTANT…CI-DESSOUS.'."\n \n".
                     'Conditions…'."\n \n".'En vous inscr…'), 'border:TLBR; colspan:5;');
$table->printRow();
```

Once again, thanks for you help!
Michel.
