### ISSUE TITLE
How can I print barcode in a cell?

### ISSUE THREAD

**Issue by gurpr33t** [fpdf-easytable/fpdf-easytable#16]

**Comment by fpdf-easytable** [comment]
If you can put the bar code in a image.

**Comment by gurpr33t** [comment]
I am trying to integrate this script with easy tables but no success.
http://www.fpdf.org/en/script/script88.php

**Comment by fpdf-easytable** [comment]
What about to use a php bar code generator that makes jpg or png so you can use those images of your bar codes in easytable...

**Comment by gurpr33t** [comment]
Like this one?
http://davidscotttufts.com/2009/03/31/how-to-create-barcodes-in-php/
