### ISSUE TITLE
Is there a way to set page size?

### ISSUE THREAD

**Issue by gurpr33t** [fpdf-easytable/fpdf-easytable#19]
Like in FPDF, there is a way to set page size like this:
`$pdf = new FPDF('P','mm','array('90','120');`

Is there a way to set the same in exFPDF?

**Comment by fpdf-easytable** [comment]
Please read FPDF documentation.

**Comment by gurpr33t** [comment]
I am asking to set in exFPDF, not in FPDF.

**Comment by fpdf-easytable** [comment]
exFPDF inherits from FPDF which means that all the methods from FPDF are available in exFPDF.
