### ISSUE TITLE
Cell Color

### ISSUE THREAD

**Issue by stepgr** [fpdf-easytable/fpdf-easytable#21]
Hi ,
 
is there a way to change a cells color (or font color )  when a value is lower or greater than a constant value ?

George

**Comment by fpdf-easytable** [comment]
Hi George,

EasyTable does not have a method to do that, however you could code a style string for example:
```
$my_special_style="....color:black";
if($tricky_value<123){
    $my_special_style="....color:red";
}

$my_table...
cell($my_special_style)...
```

**Comment by stepgr** [comment]
Thanks I 'll try that
