### ISSUE TITLE
Text Center in Cell 

### ISSUE THREAD

**Issue by stepgr** [fpdf-easytable/fpdf-easytable#22]
I didn't want to continue on other request about cell color so here it is : 
We have the option to align text L C R in cells (or headers)  but , what if I want the text to be centered both horizontal and vertical inside a cell ? Is  that possible ?

Thanks

**Comment by mdes** [comment]
> valign [C/R/T]
> 
> The property valign defines the vertical alignment of the content of the cells. The values can be:
> 
> T: top
> M: middle
> B: bottom

**Comment by stepgr** [comment]
thanks , I need to read more carefully the docs  I guess...
