### ISSUE TITLE
HTML convertion and  space between paragraphs

### ISSUE THREAD

**Issue by stepgr** [fpdf-easytable/fpdf-easytable#25]
Hi ,

I've noticed that while using the iibrary  (I can't remember if I had the issue with plain fpfd ) the produced space between html 
converted paragraphs inside a cell is too big . Is there any way to control it this space (as in html/css  for example where you can 
set a margin )  ? 

Thanks

**Comment by fpdf-easytable** [comment]
Please read the documentation.
