### ISSUE TITLE
table header do not repeat

### ISSUE THREAD

**Issue by bilouze** [fpdf-easytable/fpdf-easytable#28]
Hello,
I don't understand why my code doesn't repeat the "type" header in colspan 6, it scores well on the first page but not the following ones, but your example number 2 works fine even when I add an extend class exFPDF with the header () and footer () methods.
I don't understand where my mistake is coming from.

```
<?php
// class extends exFPDF with header() and footer() methods, array generate with mysql request
// result it's simple array
$pdf=new pdfConstructeur(); 
$pdf->AddPage();

// construction des tableaux
$write=new easyTable($pdf, '%{10, 10, 15, 10, 15, 40}', 'width:100%;align:C; font-size:6;font-family:helvetica;border:1;');
$write->easyCell('Type', 'align:C; bgcolor:#d0d0d0;font-style:B; colspan:6;');
$write->printRow();

$write->easyCell(utf8_decode('Rèf doc') , 'align:C; bgcolor:#d0d0d0; font-style:B;');
$write->easyCell('Type', 'align:C; bgcolor:#d0d0d0;font-style:B;');
$write->easyCell('Sous-ensemble', 'align:C; bgcolor:#d0d0d0;font-style:B;');
$write->easyCell('Date', 'align:C; bgcolor:#d0d0d0;font-style:B;');
$write->easyCell(utf8_decode('Matériel'), 'align:C; bgcolor:#d0d0d0;font-style:B;');
$write->easyCell('Objet', 'align:C; bgcolor:#d0d0d0;font-style:B;');
$write->printRow(true);

foreach ($result_const as $key => $value) {
   $write->easyCell(utf8_decode($value['referencement']), 'align:C;');
   $write->easyCell(utf8_decode($value['type']), 'align:C;');
   $write->easyCell(utf8_decode($value['s_ensemble']), 'align:C;');
   $write->easyCell(utf8_decode($value['date']), 'align:C;');
   $write->easyCell(utf8_decode($value['materiels']), 'align:C;');
   $write->easyCell($value['objet'], 'align:C;');
   $write->printRow();
}


$write->endTable(5);

//###############################################

 $pdf->Output();

?>
```

Thank you for your feedback.

EDIT: I'm sorry, I realized that my example is difficult to follow and not self contained. I'll try to write a better example tomorrow

**Comment by guibou** [comment]
@bilouze Don't you need a `printRow(true)` after the row definition containing the "type" line if you want it to repeat on each page?

**Comment by bilouze** [comment]
page one :
![Capture](https://user-images.githubusercontent.com/1399344/105083983-fdd2a700-5a95-11eb-845e-1f95ae134884.JPG)

page two : 
![Capture2](https://user-images.githubusercontent.com/1399344/105084008-088d3c00-5a96-11eb-95bc-581e596d4702.JPG)

You're example2.php work fine with my code.
thanks !

**Comment by fpdf-easytable** [comment]
Hi,

From the documentation one can deduce that headers can have only one row. If you look carefully the header in Example 2 is a multirow header, not two-row header. 

By the way you should have:
`
$write->easyCell('Type', 'align:C; bgcolor:#d0d0d0;font-style:B;');
$write->printRow();
`
Cheers

**Comment by bilouze** [comment]
Hi,
Thank you for your reply.

Your example does not work, even if I remove "colspan: 6", it positions on a cell and does not repeat.
But to test, I added a "rowspan: 2" and it works.
So I notice that the behavior of printRow () changes when there is a "rowspan", it does not create any additional rows.
As you tell me, this creates a multi-line header and not a two-line header.
So the solution is the rowspan.

thank you very much for your help.

sorry, my english is very bad.
