### ISSUE TITLE
Fatal error: Using $this when not in object context

### ISSUE THREAD

**Issue by Premnarayanan** [fpdf-easytable/fpdf-easytable#3]
Hello,
I am unable to run any of the examples,
while running the basic example this is the error i got
Fatal error: Using $this when not in object context in C:\xampp\htdocs\fpdf-easytable-master\easyTable.php on line 929

How to clear this error

**Comment by fpdf-easytable** [comment]
Download the fpdf class (http://www.fpdf.org/) and put the file fpdf.php in the directory fpdf-easytable-master.

**Comment by Premnarayanan** [comment]
Yes i have already added a copy of fpdf.php and i am using version 1.81

**Comment by fpdf-easytable** [comment]
Check your version of php, it should be at least 5.7.
