### ISSUE TITLE
Wrong page size and orientation at page break

### ISSUE THREAD

**Issue by soloelroy** [fpdf-easytable/fpdf-easytable#30]
# Problem
When some parameters in the _AddPage()_ method are set...
 ```php
/***** (e.g.) *****/

$pdf->AddPage("P", "Letter", 90);
```
and the table exceeds the page height, it will create a new page but it will ignore the page size and rotation.

# Fix

I fixed this by creating two public methods in the _exFPDF_ class:
```php
public function get_CurPageSize() {
  return $this->CurPageSize;
}

public function get_CurRotation() {
  return $this->CurRotation;
}
```

and modifying the _printRow()_ method in the _easyTable_ class:
```php
/***** These are the last two if statements in the printRow() method *****/

if($this->table_style['split-row']==false && $this->pdf_obj->PageBreak()<$this->pdf_obj->GetY()+max($block_height,$this->row_heights[0])){
  $this->pdf_obj->addPage($this->document_style['orientation'], $this->pdf_obj->get_CurPageSize(), $this->pdf_obj->get_CurRotation());
  if(count($this->header_row)>0){
    $this->printing_loop(true);
  }
}

if($this->new_table){
  if(count($this->header_row)>0){
    $r=$this->pdf_obj->PageBreak()-($this->pdf_obj->GetY()+$block_height);
    if($r<0 || $r<self::PBThreshold){
      $this->pdf_obj->addPage($this->document_style['orientation'], $this->pdf_obj->get_CurPageSize(), $this->pdf_obj->get_CurRotation());
    }
  }
  $this->new_table=false;
}
```
---
I'm sorry if this is not a pull request or if it even should be... I'm quite new to GIT and Github

**Comment by fpdf-easytable** [comment]
What object are you passing to the EasyTable contructor, a FPDF object or an exFPDF? For what you want to do, you need to pass exFPDF. 
If a table generated by EasyTable is bigger than the height of the page, it will AUTOMATICALLY add a new page with the same orientation of the page where the table started. 

By the way... did you notice the exFPDF actually has a public get_orientation method?
