### ISSUE TITLE
Does not handle units other than mm

### ISSUE THREAD

**Issue by FoxxMD** [fpdf-easytable/fpdf-easytable#31]
My fpdf objects are constructed with inches like `new FDPF('P', 'in', 'Letter');`

When calculating the width of cells easytable does not take into account the scale factor (`$this->k` on FPDF). I'm sure its missing in a few other places as well. Using percentages for cell width also does not work.

**Comment by fpdf-easytable** [comment]
How do you set the percentage for each cells?
