### ISSUE TITLE
Bottom border doesn't appear on split-row

### ISSUE THREAD

**Issue by jjmartinez20** [fpdf-easytable/fpdf-easytable#32]
Hello, first of all thanks for this library, it's helped me a lot building PDF files with PHP and customize them easily.

At this moment I'm trying to create a table setting the property split-row to true because the text contained in some cells may be large and I don't want to leave a big blank space on the pages, but when I generate the file, cell bottom border is not showing, but top border does on the new page as I show at the next image.

![imagen](https://user-images.githubusercontent.com/84927210/141696383-3264b36f-cfaa-400a-98d7-610c48f34fd5.png)

I don't know if this is a bug or something I'm missing in the code. I've checked the documentation, but I didn't find anything that helps me solve this.

**Comment by fpdf-easytable** [comment]
Hi, thank you for your interest in EasyTable. The example-1.pdf (example-1.php) has an example of what you tried to achieve.

**Comment by jjmartinez20** [comment]
Hi Dan, thanks for responding. 

I've seen the example 1 as you indicated, but unfortunately that's not what I need. I think I didn't explain it too well. What I want to achieve is that bottom border is shown like top border does when splitting row. The next image shows what I'd like to do, but I don't know how to do it or if it's not possible with the library.

<img width="872" alt="Bottom 2" src="https://user-images.githubusercontent.com/84927210/143148212-1511bbe5-6e85-47e7-b097-b2ec7b506dbd.png">

**Comment by fpdf-easytable** [comment]
So you want to draw the bottom/top border of a cell that split between 2 pages... That is not possible, it is because if the borders are drawn for a cell that split, visually it would look like each part of the cell is a cell on its own, which can be a bit confusing sometimes... A hack for what you want would be to make a function to draw a line (at the top or bottom of the page).

**Comment by jjmartinez20** [comment]
Oh, I see, so it's not implemented in the library. I hadn't thought about creating a function to do that. I will try it then. 

Thanks for your help Dan.
