### ISSUE TITLE
Unable to install with composer...

### ISSUE THREAD

**Issue by dilipen** [fpdf-easytable/fpdf-easytable#4]
I used following  command to install "composer install fpdf-easytable/fpdf-easytable -vvv"  on terminal mode.
I think we need to enable some enhancements...

**Comment by fpdf-easytable** [comment]
Hi, 
Thank you for you interest in EasyTable project.
I'm sorry but I'm not interested about doing anything with composer.  Why to try to fix something that is not broken? Just put the files in your project path and done. How difficult is that?

**Comment by ramanteja** [comment]
Hi, I am trying to use EasyTable in my php project. It works like a charm on my localhost but is not running on the remote server. It is not showing any errors. Just a blank screen popping up.

**Comment by Deepak7264** [comment]
I encountered the same problem, can anyone offer a solution please
