### ISSUE TITLE
php version

### ISSUE THREAD

**Issue by larafj** [fpdf-easytable/fpdf-easytable#46]
I have tested the basic_example.php on two servers: Ubuntu 18.04 (PHP 7.2.24-0ubuntu0.18.04.17) and Ubuntu 22.04 (PHP 8.1.2-1ubuntu2.18). In the first server (18.04), it works out of the box; but on the second server (22.04) I just got a blank page, both with FPDF 1.81. Could it be due to the PHP version or could there be another reason?

Thanks!

**Comment by larafj** [comment]
Confirmed with a third server where the only thing I changed was PHP version. It works with PHP 7.4 but not with PHP 8.0, 8.1, 8.2 or 8.3 (blank page). Update requirements?

**Comment by larafj** [comment]
This is the error that I get with PHP 8.0 and above: 
"Fatal error: Uncaught Error: Call to undefined function get_magic_quotes_runtime()"

**Comment by larafj** [comment]
> This is the error that I get with PHP 8.0 and above: "Fatal error: Uncaught Error: Call to undefined function get_magic_quotes_runtime()"

Solved by updating fpdf to 1.86. Update requirements for installation?

**Comment by fpdf-easytable** [comment]
Cool! 

P.S: Sorry for late replay...
