### ISSUE TITLE
Feature Request: Hyperlinks

### ISSUE THREAD

**Issue by ErikKalkoken** [fpdf-easytable/fpdf-easytable#5]
Would be great to be able to use markup to create hyperlinks within a cell, similar to the font tagging  feature. e.g. by using HTML syntax: `<a href="www.example.com">Link</a>`

**Comment by fpdf-easytable** [comment]
I will implement it soon. 

Thanks

**Comment by ErikKalkoken** [comment]
Awesome! Looking forward to it.

**Comment by fpdf-easytable** [comment]
Links feature added.

**Comment by ErikKalkoken** [comment]
many thanks for adding the feature: I will try it out tomorrow.
